name: Deploy Vite AceSchedules Site to GitHub Pages

on:
  push:
    branches: [ "God" ]
  #workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./AceSchedules_frontend

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Instalar dependências
        run: yarn install --frozen-lockfile

      - name: Build do projeto
        run: yarn build

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./AceSchedules_frontend/dist
          force_orphan: true
          commit_message: 'Deploy: {{ github.sha }}'
